# Generated by Django 5.2.1 on 2025-06-02 23:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du budget')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('period_type', models.CharField(choices=[('ME', 'Mensuel'), ('AN', 'Annuel'), ('TR', 'Trimestriel')], default='ME', max_length=2, verbose_name='Type de période')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-start_date', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'objectif")),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Cible')),
                ('current_amount_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Actuel Mis de Côté')),
                ('target_date', models.DateField(verbose_name='Date Cible')),
                ('status', models.CharField(choices=[('OU', 'Ouvert'), ('AT', 'Atteint'), ('AN', 'Annulé')], default='OU', max_length=2, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_goals', to='core.category', verbose_name='Catégorie liée (optionnel)')),
            ],
            options={
                'verbose_name': "Objectif d'Épargne",
                'verbose_name_plural': "Objectifs d'Épargne",
                'ordering': ['target_date', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('transaction_type', models.CharField(choices=[('DE', 'Dépense'), ('RE', 'Revenu')], default='DE', max_length=2, verbose_name='Type de transaction')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
