# Generated by Django 5.2.1 on 2025-06-03 21:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du compte')),
                ('currency', models.CharField(default='CHF', max_length=3, verbose_name='Devise')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Solde initial')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['start_date', 'category__name'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('category', 'period_type', 'start_date')},
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Budgété'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Fin (optionnel)'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period_type',
            field=models.CharField(choices=[('M', 'Mensuel'), ('Y', 'Annuel')], default='M', max_length=1, verbose_name='Type de Période'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='start_date',
            field=models.DateField(verbose_name='Date de Début'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Revenu'), ('OUT', 'Dépense'), ('TRF', 'Transfert')], default='OUT', max_length=3, verbose_name='Type de transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account', verbose_name='Compte'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='budget',
            name='is_active',
        ),
    ]
