# Generated by Django 5.2.1 on 2025-06-04 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_pattern', models.CharField(max_length=255, unique=True, verbose_name='Modèle de description')),
                ('last_applied_at', models.DateTimeField(auto_now=True, verbose_name='Dernière application')),
                ('hit_count', models.IntegerField(default=1, verbose_name="Nombre d'occurrences")),
                ('suggested_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorization_rules', to='webapp.category', verbose_name='Catégorie suggérée')),
                ('suggested_tags', models.ManyToManyField(blank=True, related_name='categorization_rules', to='webapp.tag', verbose_name='Tags suggérés')),
            ],
            options={
                'verbose_name': 'Règle de Catégorisation',
                'verbose_name_plural': 'Règles de Catégorisation',
                'ordering': ['-hit_count', '-last_applied_at'],
            },
        ),
    ]
