# Generated by Django 5.2.1 on 2025-06-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_categorizationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_allocated_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='La somme des montants alloués aux fonds.', max_digits=15, verbose_name='Montant total alloué')),
                ('notes', models.TextField(blank=True, help_text='Détails ou commentaires sur cette opération de ventilation.', verbose_name="Notes sur l'allocation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('transaction', models.OneToOneField(help_text='La transaction de revenu (ex: virement salarial) qui est ventilée.', on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='webapp.transaction', verbose_name='Transaction de revenu associée')),
            ],
            options={
                'verbose_name': 'Allocation de Fonds',
                'verbose_name_plural': 'Allocations de Fonds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Le montant alloué à cette catégorie de fonds.', max_digits=15, verbose_name='Montant alloué')),
                ('notes', models.TextField(blank=True, help_text="Notes spécifiques à cette ligne d'allocation.", verbose_name='Notes de ligne')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='webapp.allocation', verbose_name='Allocation parente')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_lines', to='webapp.category', verbose_name='Catégorie de fonds')),
            ],
            options={
                'verbose_name': "Ligne d'Allocation",
                'verbose_name_plural': "Lignes d'Allocation",
                'ordering': ['category__name'],
                'unique_together': {('allocation', 'category')},
            },
        ),
    ]
