# Generated by Django 5.2.1 on 2025-06-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_allocation_allocationline'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individuel'), ('COMMON', 'Commun'), ('SAVINGS', 'Épargne'), ('OTHER', 'Autre')], default='INDIVIDUAL', help_text="Définissez si ce compte est individuel, commun, d'épargne, etc.", max_length=10, verbose_name='Type de compte'),
        ),
    ]
