# Generated by Django 5.2.1 on 2025-06-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_fund_managed',
            field=models.BooleanField(default=False, help_text='Cochez si vous souhaitez gérer un fonds/une enveloppe spécifique pour cette catégorie (solde cumulatif).', verbose_name='Gérer un fonds dédié'),
        ),
    ]
