# Generated by Django 5.2.1 on 2025-06-05 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_category_is_fund_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDebitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debited_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='La somme des montants débités des fonds.', max_digits=15, verbose_name='Montant total débité des fonds')),
                ('notes', models.TextField(blank=True, help_text='Détails ou commentaires sur cette opération de débit.', verbose_name='Notes sur le débit de fonds')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('transaction', models.OneToOneField(help_text='La transaction de dépense qui est débitée des fonds.', on_delete=django.db.models.deletion.CASCADE, related_name='fund_debit_record', to='webapp.transaction', verbose_name='Transaction de dépense associée')),
            ],
            options={
                'verbose_name': 'Débit de Fonds',
                'verbose_name_plural': 'Débits de Fonds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundDebitLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Le montant débité de cette catégorie de fonds.', max_digits=15, verbose_name='Montant débité')),
                ('notes', models.TextField(blank=True, help_text='Notes spécifiques à cette ligne de débit.', verbose_name='Notes de ligne')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_debit_lines', to='webapp.category', verbose_name='Catégorie de fonds')),
                ('fund_debit_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='webapp.funddebitrecord', verbose_name='Enregistrement de débit de fonds parent')),
            ],
            options={
                'verbose_name': 'Ligne de Débit de Fonds',
                'verbose_name_plural': 'Lignes de Débit de Fonds',
                'ordering': ['category__name'],
                'unique_together': {('fund_debit_record', 'category')},
            },
        ),
    ]
