# Generated by Django 5.2.1 on 2025-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_funddebitrecord_funddebitline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_budgeted',
            field=models.BooleanField(default=False, help_text='Indique si cette catégorie est associée à un budget planifié.', verbose_name='Catégorie budgétisée'),
        ),
    ]
