# Generated by Django 5.2.1 on 2025-06-12 00:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household_type', models.CharField(choices=[('SINGLE', 'Personne seule'), ('COUPLE_SHARED', 'Couple - Tout partagé'), ('COUPLE_MIXED', 'Couple - Comptes mixtes'), ('COUPLE_SEPARATE', 'Couple - Comptes séparés'), ('FAMILY_SHARED', 'Famille - Tout partagé'), ('FAMILY_MIXED', 'Famille - Comptes mixtes'), ('ROOMMATES', 'Colocation'), ('CUSTOM', 'Configuration personnalisée')], default='SINGLE', help_text='Détermine les paramètres de partage par défaut', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_all_transactions',
            field=models.BooleanField(default=False, help_text='Peut modifier les transactions de tous les utilisateurs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all_categories',
            field=models.BooleanField(default=False, help_text='Peut voir les catégories de tous les utilisateurs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_all_transactions',
            field=models.BooleanField(default=False, help_text='Peut voir les transactions de tous les utilisateurs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, help_text='Utilisateurs spécifiques avec qui partager les données', related_name='shared_access_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEMBER', 'Membre'), ('VIEWER', 'Observateur')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='webapp.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('household', 'user')},
            },
        ),
    ]
